# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

#Another option for trigger
#on:
  #release:
    #types: [created]

name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      #-
        #name: Login to Docker Hub
        #uses: docker/login-action@v2
        #with:
          #username: ${{ secrets.DOCKERHUB_USERNAME }}
          #password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: avieltovim/java-app:latest

    #permissions:
     # contents: read
      #packages: write

#        java-version: '11'
 #       distribution: 'temurin'
  #      server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
   #     settings-path: ${{ github.workspace }} # location for the settings.xml file

#      run: mvn -B package --file pom.xml
 #     env:
  #      GITHUB_TOKEN: ${{ github.token }}
